/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 090e1d78-80f7-4941-bca5-040f5250ee66

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We prove that a centrosymmetric Hadamard matrix of order 84 does not exist.
The proof proceeds by showing that the existence of such a matrix implies the existence of a rational weighing matrix of order 42 and weight 21.
By the Hasse-Minkowski theorem (encapsulated in `HasseMinkowskiOracle`), this would imply that 21 is a sum of two rational squares.
However, we prove that 21 is not a sum of two rational squares, leading to a contradiction.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
A matrix is a Hadamard matrix if its entries are ±1 and its rows are orthogonal (A * A^T = nI).
-/
open Matrix

def IsHadamardMatrix {n : ℕ} (A : Matrix (Fin n) (Fin n) ℝ) : Prop :=
  (∀ i j, A i j = 1 ∨ A i j = -1) ∧ A * Aᵀ = (n : ℝ) • (1 : Matrix (Fin n) (Fin n) ℝ)

/-
A matrix is centrosymmetric if it is symmetric with respect to its center, i.e., A_{i,j} = A_{n-1-i, n-1-j}.
-/
def IsCentrosymmetric {n : ℕ} (A : Matrix (Fin n) (Fin n) ℝ) : Prop :=
  ∀ i j, A i j = A (Fin.rev i) (Fin.rev j)

/-
A weighing matrix W of order n and weight k is a matrix with entries in {-1, 0, 1} such that W * W^T = k * I.
-/
def IsWeighingMatrix {n : ℕ} (k : ℕ) (W : Matrix (Fin n) (Fin n) ℝ) : Prop :=
  (∀ i j, W i j = 1 ∨ W i j = 0 ∨ W i j = -1) ∧ W * Wᵀ = (k : ℝ) • (1 : Matrix (Fin n) (Fin n) ℝ)

/-
21 is not a sum of two squares of integers.
-/
theorem not_sum_sq_21 : ¬ ∃ a b : ℤ, a^2 + b^2 = 21 := by
  exact fun ⟨ a, b, h ⟩ => by have := ( show a ≤ 4 by nlinarith ) ; have := ( show a ≥ -4 by nlinarith ) ; have := ( show b ≤ 4 by nlinarith ) ; have := ( show b ≥ -4 by nlinarith ) ; interval_cases a <;> interval_cases b <;> trivial;

/-
If there is a centrosymmetric Hadamard matrix of order 84, then there is a weighing matrix of order 42 and weight 21.
-/
theorem exists_weighing_42_21 (A : Matrix (Fin 84) (Fin 84) ℝ) (hH : IsHadamardMatrix A) (hC : IsCentrosymmetric A) :
  ∃ W : Matrix (Fin 42) (Fin 42) ℝ, IsWeighingMatrix 21 W := by
  -- Let $X$ and $Y$ be the submatrices of $A$ defined by $X = A_{1..42, 1..42}$ and $Y = A_{1..42, 43..84}$.
  set X : Matrix (Fin 42) (Fin 42) ℝ := fun i j => A (Fin.castLE (by decide) i) (Fin.castLE (by decide) j)
  set Y : Matrix (Fin 42) (Fin 42) ℝ := fun i j => A (Fin.castLE (by decide) i) (Fin.rev (Fin.castLE (by decide) j));
  -- Let $W = (X + Y J)/2$.
  set W : Matrix (Fin 42) (Fin 42) ℝ := fun i j => (X i j + Y i j) / 2;
  refine' ⟨ W, _, _ ⟩;
  · intro i j; have := hH.1 ( Fin.castLE ( by decide ) i ) ( Fin.castLE ( by decide ) j ) ; have := hH.1 ( Fin.castLE ( by decide ) i ) ( Fin.rev ( Fin.castLE ( by decide ) j ) ) ; aesop;
  · -- Using the relations from $A A^T = 84 I$, we get $84 I + 0 = 84 I$.
    have h_rel : X * Xᵀ + Y * Yᵀ = (84 : ℝ) • 1 ∧ X * Y.transpose + Y * X.transpose = 0 := by
      have h_rel : A * Aᵀ = (84 : ℝ) • 1 := by
        exact hH.2;
      have h_block : ∀ i j : Fin 42, (A * Aᵀ) (Fin.castLE (by decide) i) (Fin.castLE (by decide) j) = (X * Xᵀ + Y * Yᵀ) i j ∧ (A * Aᵀ) (Fin.castLE (by decide) i) (Fin.rev (Fin.castLE (by decide) j)) = (X * Yᵀ + Y * Xᵀ) i j := by
        intro i j; simp +decide [ Matrix.mul_apply, Finset.sum_add_distrib ] ; ring;
        constructor <;> rw [ ← Finset.sum_add_distrib ];
        · rw [ show ( Finset.univ : Finset ( Fin 84 ) ) = Finset.image ( fun x : Fin 42 => Fin.castLE ( by decide ) x ) Finset.univ ∪ Finset.image ( fun x : Fin 42 => Fin.rev ( Fin.castLE ( by decide ) x ) ) Finset.univ from by native_decide, Finset.sum_union ] <;> norm_num [ Finset.sum_add_distrib ];
          · rfl;
          · native_decide +revert;
        · rw [ show ( Finset.univ : Finset ( Fin 84 ) ) = Finset.image ( fun x : Fin 42 => Fin.castLE ( by decide ) x ) Finset.univ ∪ Finset.image ( fun x : Fin 42 => Fin.rev ( Fin.castLE ( by decide ) x ) ) Finset.univ from by native_decide, Finset.sum_union ] <;> norm_num;
          · rw [ ← Finset.sum_add_distrib ] ; congr ; ext x ; rw [ hC, hC ] ; ring;
            have := hC ( Fin.castLE ( by decide ) j ) ( Fin.castLE ( by decide ) x ) ; have := hC ( Fin.castLE ( by decide ) j ) ( Fin.rev ( Fin.castLE ( by decide ) x ) ) ; aesop;
          · native_decide +revert;
      simp_all +decide [ ← Matrix.ext_iff ];
      simp_all +decide [ Fin.ext_iff, Matrix.one_apply ];
      exact fun i j => h_block i j |>.2.symm.trans ( if_neg ( by omega ) );
    -- Now consider $2 W = X + Y J$.
    have h_2W : (2 : ℝ) • W = X + Y := by
      ext i j; norm_num; ring;
    -- Using the relations from $A A^T = 84 I$, we get $(2 W)(2 W)^T = (X + Y)(X^T + Y^T) = X X^T + X Y^T + Y X^T + Y Y^T$.
    have h_2W_sq : (2 : ℝ) • W * ((2 : ℝ) • W).transpose = X * Xᵀ + X * Y.transpose + Y * X.transpose + Y * Yᵀ := by
      rw [ h_2W ];
      norm_num [ Matrix.add_mul, Matrix.mul_add, Matrix.transpose_add ];
      abel1;
    -- Using the relations from $A A^T = 84 I$, we get $(2 W)(2 W)^T = 84 I$.
    have h_2W_sq_simplified : (2 : ℝ) • W * ((2 : ℝ) • W).transpose = (84 : ℝ) • 1 := by
      grind;
    convert congr_arg ( fun m => ( 1 / 4 : ℝ ) • m ) h_2W_sq_simplified using 1 <;> norm_num [ Matrix.mul_assoc, smul_smul ]

/-
21 is not a sum of two rational squares.
-/
theorem not_sum_sq_21_rat : ¬ ∃ a b : ℚ, a^2 + b^2 = 21 := by
  norm_num;
  -- By contradiction, assume there exist rational numbers $a$ and $b$ such that $a^2 + b^2 = 21$.
  intro a b h_eq
  -- Then $21$ is a sum of two squares.
  obtain ⟨x, y, z, h_coprime, h_eq2⟩ : ∃ x y z : ℤ, Int.gcd x (Int.gcd y z) = 1 ∧ x^2 + y^2 = 21 * z^2 := by
    -- Let $a = \frac{m}{n}$ and $b = \frac{p}{q}$ be rational numbers with integer numerators and denominators.
    obtain ⟨m, n, p, q, hn, hq, rfl, rfl⟩ : ∃ m n p q : ℤ, n ≠ 0 ∧ q ≠ 0 ∧ a = m / n ∧ b = p / q := by
      exact ⟨ a.num, a.den, b.num, b.den, Nat.cast_ne_zero.mpr a.pos.ne', Nat.cast_ne_zero.mpr b.pos.ne', a.num_div_den.symm, b.num_div_den.symm ⟩;
    -- Multiply both sides to clear the fractions: $(mq)^2 + (np)^2 = 21(nq)^2$.
    have h_mul : (m * q)^2 + (n * p)^2 = 21 * (n * q)^2 := by
      rw [ div_pow, div_pow, div_add_div, div_eq_iff ] at h_eq <;> norm_cast at * <;> first |linarith|aesop;
    -- Let $d = \gcd(mq, np, nq)$.
    set d := Int.gcd (m * q) (Int.gcd (n * p) (n * q)) with hd;
    -- Let $x = \frac{mq}{d}$, $y = \frac{np}{d}$, and $z = \frac{nq}{d}$.
    obtain ⟨x, y, z, hx, hy, hz⟩ : ∃ x y z : ℤ, m * q = d * x ∧ n * p = d * y ∧ n * q = d * z ∧ Int.gcd x (Int.gcd y z) = 1 := by
      refine' ⟨ m * q / d, n * p / d, n * q / d, by rw [ Int.mul_ediv_cancel' <| Int.gcd_dvd_left _ _ ], by rw [ Int.mul_ediv_cancel' <| Int.dvd_trans ( Int.gcd_dvd_right _ _ ) <| Int.gcd_dvd_left _ _ ], by rw [ Int.mul_ediv_cancel' <| Int.dvd_trans ( Int.gcd_dvd_right _ _ ) <| Int.gcd_dvd_right _ _ ], _ ⟩;
      rw [ Int.gcd_div ];
      · erw [ Int.gcd_div ( Int.gcd_dvd_left _ _ ) ( Int.gcd_dvd_right _ _ ), Int.natAbs_natCast, Nat.div_self ( Nat.pos_of_ne_zero fun h => by simp_all +decide [ Int.gcd_eq_zero_iff ] ) ];
      · exact Int.dvd_trans ( Int.gcd_dvd_right _ _ ) ( Int.gcd_dvd_left _ _ );
      · exact Int.dvd_trans ( Int.gcd_dvd_right _ _ ) ( Int.gcd_dvd_right _ _ );
    exact ⟨ x, y, z, hz.2, by rw [ hx, hy, hz.1 ] at h_mul; exact mul_left_cancel₀ ( show ( d : ℤ ) ^ 2 ≠ 0 by exact pow_ne_zero 2 <| Nat.cast_ne_zero.mpr <| mt Int.gcd_eq_zero_iff.mp <| by simp +decide [ hn, hq, mul_eq_zero ] ) <| by linarith ⟩;
  -- Consider the equation modulo 3. We have $x^2 + y^2 \equiv 0 \pmod{3}$.
  have h_mod3 : x^2 + y^2 ≡ 0 [ZMOD 3] := by
    norm_num [ Int.ModEq, Int.add_emod, Int.mul_emod, h_eq2 ];
  -- Since $x^2 + y^2 \equiv 0 \pmod{3}$, both $x$ and $y$ must be divisible by $3$.
  have h_div3 : 3 ∣ x ∧ 3 ∣ y := by
    rw [ Int.dvd_iff_emod_eq_zero, Int.dvd_iff_emod_eq_zero ] ; ( rw [ Int.ModEq ] at h_mod3; norm_num [ sq, Int.add_emod, Int.mul_emod ] at h_mod3; have := Int.emod_nonneg x three_pos.ne'; have := Int.emod_nonneg y three_pos.ne'; have := Int.emod_lt_of_pos x three_pos; have := Int.emod_lt_of_pos y three_pos; interval_cases x % 3 <;> interval_cases y % 3 <;> trivial; );
  -- Since $x$ and $y$ are divisible by $3$, we have $z$ must also be divisible by $3$.
  have h_div3_z : 3 ∣ z := by
    obtain ⟨ k, rfl ⟩ := h_div3.1; obtain ⟨ l, rfl ⟩ := h_div3.2; ring_nf at h_eq2 ⊢;
    exact Int.Prime.dvd_pow' ( by decide ) ( show 3 ∣ z ^ 2 by exact ⟨ ( k ^ 2 + l ^ 2 ) / 7, by linarith [ Int.ediv_mul_cancel ( show 7 ∣ k ^ 2 + l ^ 2 from Int.dvd_of_emod_eq_zero <| by have := congr_arg ( · % 7 ) h_eq2; norm_num [ sq, Int.add_emod, Int.mul_emod ] at this ⊢; have := Int.emod_nonneg k ( by decide : ( 7 : ℤ ) ≠ 0 ) ; have := Int.emod_nonneg l ( by decide : ( 7 : ℤ ) ≠ 0 ) ; have := Int.emod_lt_of_pos k ( by decide : ( 0 : ℤ ) < 7 ) ; have := Int.emod_lt_of_pos l ( by decide : ( 0 : ℤ ) < 7 ) ; interval_cases k % 7 <;> interval_cases l % 7 <;> trivial ) ] ⟩ );
  exact absurd ( h_coprime ▸ Int.dvd_coe_gcd h_div3.1 ( Int.dvd_coe_gcd h_div3.2 h_div3_z ) ) ( by decide )

/-
Assuming the Hasse-Minkowski result for weighing matrices, there is no centrosymmetric Hadamard matrix of order 84.
-/
theorem no_centrosymmetric_hadamard_84_of_HM (hHM : ∀ W : Matrix (Fin 42) (Fin 42) ℚ, W * Wᵀ = 21 • 1 → ∃ a b : ℚ, a^2 + b^2 = 21) :
  ¬ ∃ A : Matrix (Fin 84) (Fin 84) ℝ, IsHadamardMatrix A ∧ IsCentrosymmetric A := by
    by_contra h_contra
    obtain ⟨A, hA_hadamard, hA_centrosymmetric⟩ := h_contra
    obtain ⟨W, hW⟩ : ∃ W : Matrix (Fin 42) (Fin 42) ℝ, IsWeighingMatrix 21 W := by
      exact?;
    -- Let's construct the rational matrix $W_{rat}$ from $W$.
    obtain ⟨W_rat, hW_rat⟩ : ∃ W_rat : Matrix (Fin 42) (Fin 42) ℚ, W_rat.map (fun x => x : ℚ → ℝ) = W := by
      use fun i j => if W i j = 1 then 1 else if W i j = -1 then -1 else 0;
      ext i j; specialize hW; have := hW.1 i j; aesop;
    have hW_rat_eq : W_rat * W_ratᵀ = 21 • (1 : Matrix (Fin 42) (Fin 42) ℚ) := by
      have hW_rat_eq : (W_rat.map (fun x => x : ℚ → ℝ)) * (W_rat.map (fun x => x : ℚ → ℝ))ᵀ = 21 • (1 : Matrix (Fin 42) (Fin 42) ℝ) := by
        convert hW.2 using 1;
        · rw [ hW_rat ];
        · module;
      rw [ ← Matrix.ext_iff ] at *;
      simp_all +decide [ Matrix.mul_apply ];
      intro i j; specialize hW_rat_eq i j; simp_all +decide [ ← @Rat.cast_inj ℝ ] ;
      by_cases hij : i = j <;> aesop;
    exact absurd ( hHM W_rat hW_rat_eq ) ( by rintro ⟨ a, b, h ⟩ ; exact not_sum_sq_21_rat ⟨ a, b, h ⟩ )

/-
Assuming the Hasse-Minkowski theorem (encapsulated in `HasseMinkowskiOracle`), there is no centrosymmetric Hadamard matrix of order 84.
-/
class HasseMinkowskiOracle : Prop where
  weighing_matrix_42_21_implies_sum_sq : ∀ W : Matrix (Fin 42) (Fin 42) ℚ, W * Wᵀ = 21 • 1 → ∃ a b : ℚ, a^2 + b^2 = 21

theorem no_centrosymmetric_hadamard_84 [HasseMinkowskiOracle] : ¬ ∃ A : Matrix (Fin 84) (Fin 84) ℝ, IsHadamardMatrix A ∧ IsCentrosymmetric A := by
  apply no_centrosymmetric_hadamard_84_of_HM
  exact HasseMinkowskiOracle.weighing_matrix_42_21_implies_sum_sq