/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 6a7c2eef-fb6f-479a-8c76-0077095a1245

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
A set A is reciprocal sum free if for all distinct a, b, c in A, 1/a is not equal to 1/b + 1/c.
-/
open Set Finset

/-- A set of natural numbers is reciprocal sum free if there are no distinct elements a, b, c
such that 1/a = 1/b + 1/c. -/
def ReciprocalSumFree (A : Set ℕ) : Prop :=
  ∀ a ∈ A, ∀ b ∈ A, ∀ c ∈ A, a ≠ b → a ≠ c → b ≠ c → (1 : ℚ) / a ≠ 1 / b + 1 / c

/-
f(N) is the maximum size of a subset of {1, ..., N} that is reciprocal sum free.
-/
noncomputable def f (N : ℕ) : ℕ := sSup {n | ∃ A : Finset ℕ, A ⊆ Finset.Icc 1 N ∧ ReciprocalSumFree (A : Set ℕ) ∧ A.card = n}

/-
f(N) is at least (N+1)/2.
-/
lemma lower_bound (N : ℕ) : f N ≥ (N + 1) / 2 := by
  have h_A_def : ∃ A : Finset ℕ, A ⊆ Finset.Icc 1 N ∧ ReciprocalSumFree (A : Set ℕ) ∧ (Finset.card A) = Nat.succ N / 2 := by
    by_contra h_contra;
    -- Let $A = \{ \lfloor N/2 \rfloor + 1, \ldots, N \}$.
    set A : Finset ℕ := Finset.Icc (N / 2 + 1) N;
    refine' h_contra ⟨ A, _, _, _ ⟩ <;> norm_num;
    · exact Finset.Icc_subset_Icc ( by norm_num ) le_rfl;
    · intro a ha b hb c hc hab hbc hca h; simp_all +decide [ div_eq_iff ] ;
      rw [ inv_add_inv, inv_eq_one_div, div_eq_div_iff ] at h <;> norm_cast at * <;> nlinarith [ Finset.mem_Icc.mp ha, Finset.mem_Icc.mp hb, Finset.mem_Icc.mp hc, Nat.div_add_mod N 2, Nat.mod_lt N two_pos ];
    · simp +zetaDelta at *;
      omega;
  exact le_csSup ⟨ N, by rintro n ⟨ A, hA₁, hA₂, rfl ⟩ ; exact le_trans ( Finset.card_le_card hA₁ ) ( by simpa ) ⟩ ⟨ _, h_A_def.choose_spec.1, h_A_def.choose_spec.2.1, h_A_def.choose_spec.2.2 ⟩

/-
The equation 1/a = 1/b + 1/c is equivalent to (b-a)(c-a) = a^2 for positive integers a, b, c with b, c > a.
-/
lemma solutions_eq {a b c : ℕ} (ha : a ≠ 0) (hb : b ≠ 0) (hc : c ≠ 0) (hba : a < b) (hca : a < c) :
  (1 : ℚ) / a = 1 / b + 1 / c ↔ (b - a) * (c - a) = a ^ 2 := by
  field_simp;
  norm_cast; constructor <;> intro h <;> nlinarith only [ Nat.sub_add_cancel ( by linarith : a ≤ b ), Nat.sub_add_cancel ( by linarith : a ≤ c ), h ] ;