/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f4632268-658f-49ec-9145-47afeb954a83
-/

/-
We prove the Gauss formula `1 + 2 + ... + n = n * (n + 1) / 2` for all natural numbers `n`.
This is formalized as `∑ i ∈ Finset.range (n + 1), i = n * (n + 1) / 2`.
The proof utilizes the existing Mathlib theorem `Finset.sum_range_id`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check Finset.sum_range_id

/-
The sum of the first n natural numbers is n(n+1)/2.
-/
theorem gauss_sum (n : ℕ) : ∑ i ∈ Finset.range (n + 1), i = n * (n + 1) / 2 := by
  simp +arith +decide [ mul_comm, Finset.sum_range_id ]