/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 89ddf6ba-8331-4aac-9850-d3d0f93864dd

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have defined Goldbach's conjecture and the condition for a counterexample. I proved that the existence of a counterexample would disprove the conjecture. I attempted to find a counterexample using the ATP, but it was unable to find one. I then proved that Goldbach's conjecture holds for all even integers up to 5000. As Goldbach's conjecture is a famous open problem believed to be true, a disproof is not currently possible.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Goldbach's conjecture states that every even integer greater than 2 is the sum of two primes.
-/
def GoldbachConjecture : Prop := ∀ n, Even n → n > 2 → ∃ p q, Nat.Prime p ∧ Nat.Prime q ∧ n = p + q

/-
A number $n$ satisfies the Goldbach counterexample condition if it is an even integer greater than 2, and for every prime $p \le n/2$, $n-p$ is not prime.
-/
def GoldbachCounterexampleCondition (n : Nat) : Prop := Even n ∧ n > 2 ∧ ∀ p, Nat.Prime p → p ≤ n / 2 → ¬ Nat.Prime (n - p)

/-
If there exists a number satisfying the Goldbach counterexample condition, then Goldbach's conjecture is false.
-/
theorem exists_counterexample_implies_disproof : (∃ n, GoldbachCounterexampleCondition n) → ¬ GoldbachConjecture := by
  rintro ⟨ n, hn ⟩ H;
  obtain ⟨ p, q, hp, hq, h ⟩ := H n hn.1 hn.2.1;
  -- Since $p$ and $q$ are primes and $n = p + q$, one of them must be less than or equal to $n/2$.
  have h_le : p ≤ n / 2 ∨ q ≤ n / 2 := by
    omega;
  cases h_le <;> have := hn.2.2 <;> aesop

/-
Goldbach's conjecture holds for all even integers $n$ such that $2 < n \le 100$.
-/
theorem GoldbachHoldsUpTo100 : ∀ n, Even n → 2 < n → n ≤ 100 → ∃ p q, Nat.Prime p ∧ Nat.Prime q ∧ n = p + q := by
  intros n hn hn' hn'';
  -- We need to check all primes $p$ less than or equal to $n/2$ to see if $n-p$ is also prime.
  have h_check : ∃ p ∈ Finset.Icc 2 (n / 2), Nat.Prime p ∧ Nat.Prime (n - p) := by
    interval_cases n <;> trivial;
  obtain ⟨ p, hp₁, hp₂, hp₃ ⟩ := h_check; exact ⟨ p, n - p, hp₂, hp₃, by rw [ Nat.add_sub_of_le ( by linarith [ Finset.mem_Icc.mp hp₁, Nat.div_mul_le_self n 2 ] ) ] ⟩ ;

/-
Goldbach's conjecture holds for all even integers $n$ such that $2 < n \le 1000$.
-/
theorem GoldbachHoldsUpTo1000 : ∀ n, Even n → 2 < n → n ≤ 1000 → ∃ p q, Nat.Prime p ∧ Nat.Prime q ∧ n = p + q := by
  norm_num +zetaDelta at *;
  -- We can prove this by checking each even number from 4 to 1000 and verifying that it can be written as the sum of two primes.
  have h_check : ∀ n ∈ Finset.filter (fun n => Even n ∧ 2 < n ∧ n ≤ 1000) (Finset.range 1001), ∃ p ∈ Finset.filter Nat.Prime (Finset.range 1001), ∃ q ∈ Finset.filter Nat.Prime (Finset.range 1001), n = p + q := by
    native_decide;
  exact fun n hn hn' hn'' => by obtain ⟨ p, hp, q, hq, rfl ⟩ := h_check n ( Finset.mem_filter.mpr ⟨ Finset.mem_range.mpr ( by linarith ), hn, hn', hn'' ⟩ ) ; exact ⟨ p, Finset.mem_filter.mp hp |>.2, q, Finset.mem_filter.mp hq |>.2, rfl ⟩ ;

/-
Goldbach's conjecture holds for all even integers $n$ such that $2 < n \le 2000$.
-/
theorem GoldbachHoldsUpTo2000 : ∀ n, Even n → 2 < n → n ≤ 2000 → ∃ p q, Nat.Prime p ∧ Nat.Prime q ∧ n = p + q := by
  intro n h₀ h₁ h₂;
  have h_step : ∀ n ∈ Finset.Icc 4 2000, Even n → ∃ p ∈ Finset.filter Nat.Prime (Finset.range (n + 1)), Nat.Prime (n - p) := by
    native_decide;
  rcases h_step n ( Finset.mem_Icc.mpr ⟨ by linarith [ show n ≥ 4 by contrapose! h₀; interval_cases n ; trivial ], h₂ ⟩ ) h₀ with ⟨ p, hp₁, hp₂ ⟩ ; exact ⟨ p, n - p, Finset.mem_filter.mp hp₁ |>.2, hp₂, by rw [ add_tsub_cancel_of_le ( by linarith [ Finset.mem_range.mp ( Finset.mem_filter.mp hp₁ |>.1 ) ] ) ] ⟩

/-
Goldbach's conjecture holds for all even integers $n$ such that $2 < n \le 5000$.
-/
theorem GoldbachHoldsUpTo5000 : ∀ n, Even n → 2 < n → n ≤ 5000 → ∃ p q, Nat.Prime p ∧ Nat.Prime q ∧ n = p + q := by
  norm_num +zetaDelta at *;
  -- Since we're working with a finite set of even n (from 4 to 5000), we can precompute all primes up to 5000 and then check for each even n whether there exists a prime p such that n - p is also prime.
  have h_primes : ∀ n ∈ Finset.filter (fun n => Even n ∧ 2 < n ∧ n ≤ 5000) (Finset.range 5001), ∃ p ∈ Finset.filter Nat.Prime (Finset.range 5001), ∃ q ∈ Finset.filter Nat.Prime (Finset.range 5001), n = p + q := by
    native_decide;
  exact fun n hn hn' hn'' => by obtain ⟨ p, hp, q, hq, rfl ⟩ := h_primes n ( Finset.mem_filter.mpr ⟨ Finset.mem_range.mpr ( by linarith ), hn, hn', hn'' ⟩ ) ; exact ⟨ p, Finset.mem_filter.mp hp |>.2, q, Finset.mem_filter.mp hq |>.2, rfl ⟩ ;