/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: c051f5b3-4436-4be1-bcd6-11c0c0cb7af4

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the area of a triangle in the Euclidean plane as the volume of its convex hull. We then prove that the area of the medial triangle (formed by the midpoints of the sides) is 1/4 of the area of the original triangle. This is achieved by showing that the medial triangle is the image of the original triangle under a homothety centered at the centroid with ratio -1/2, and using the property that volume scales by $|r|^d$ under a homothety of ratio $r$ in $d$ dimensions.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The area of a triangle with vertices p1, p2, p3 is the volume of the convex hull of {p1, p2, p3}.
-/
open MeasureTheory Set Affine
open scoped Real

noncomputable def triangleArea (p1 p2 p3 : EuclideanSpace ℝ (Fin 2)) : ℝ :=
  (volume (convexHull ℝ {p1, p2, p3})).toReal

/-
The set of vertices of the medial triangle is the image of the set of vertices of the original triangle under a homothety centered at the centroid with ratio -1/2.
-/
theorem medial_triangle_image (p1 p2 p3 : EuclideanSpace ℝ (Fin 2)) :
  let m12 := midpoint ℝ p1 p2
  let m23 := midpoint ℝ p2 p3
  let m31 := midpoint ℝ p3 p1
  let f : EuclideanSpace ℝ (Fin 2) →ᵃ[ℝ] EuclideanSpace ℝ (Fin 2) :=
    AffineMap.homothety ((1 / 3 : ℝ) • (p1 + p2 + p3)) (-1 / 2 : ℝ)
  f '' {p1, p2, p3} = {m12, m23, m31} := by
    ext; norm_num [ AffineMap.homothety ];
    norm_num [ midpoint_eq_smul_add ] ; ring;
    exact ⟨ fun h => by rcases h with ( h | h | h ) <;> first | exact Or.inl <| by ext ; have := congr_fun h ‹_› ; norm_num at * ; linarith | exact Or.inr <| Or.inl <| by ext ; have := congr_fun h ‹_› ; norm_num at * ; linarith | exact Or.inr <| Or.inr <| by ext ; have := congr_fun h ‹_› ; norm_num at * ; linarith, fun h => by rcases h with ( h | h | h ) <;> first | exact Or.inl <| by ext ; have := congr_fun h ‹_› ; norm_num at * ; linarith | exact Or.inr <| Or.inl <| by ext ; have := congr_fun h ‹_› ; norm_num at * ; linarith | exact Or.inr <| Or.inr <| by ext ; have := congr_fun h ‹_› ; norm_num at * ; linarith ⟩

/-
The area of the medial triangle is 1/4 of the area of the original triangle.
-/
theorem medial_triangle_area (p1 p2 p3 : EuclideanSpace ℝ (Fin 2)) :
  let m12 := midpoint ℝ p1 p2
  let m23 := midpoint ℝ p2 p3
  let m31 := midpoint ℝ p3 p1
  triangleArea m12 m23 m31 = (1/4) * triangleArea p1 p2 p3 := by
    field_simp;
    unfold triangleArea;
    -- The convex hull of the midpoints is the image of the convex hull of the vertices under the homothety.
    have h_convex_hull : convexHull ℝ {midpoint ℝ p1 p2, midpoint ℝ p2 p3, midpoint ℝ p3 p1} = (AffineMap.homothety ((1 / 3 : ℝ) • (p1 + p2 + p3)) (-1 / 2 : ℝ)) '' (convexHull ℝ {p1, p2, p3}) := by
      rw [ ← medial_triangle_image ];
      exact?;
    rw [ h_convex_hull ];
    erw [ MeasureTheory.Measure.addHaar_image_homothety ] ; norm_num;
    ring