/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 135fce6b-a155-40b3-95a4-601e3e709d3b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We proved that the sum of the first $n$ consecutive cubes is the square of a rational number. Specifically, we showed that $\sum_{i=0}^n i^3 = (n(n+1)/2)^2$, and since $n(n+1)/2$ is a rational number, the sum is a square of a rational number.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The sum of the first n consecutive cubes is a square of a rational number.
-/
theorem sum_cubes_is_square_of_rational (n : ℕ) : ∃ q : ℚ, (∑ i ∈ Finset.range (n + 1), (i : ℚ) ^ 3) = q ^ 2 := by
  -- We'll use that the sum of cubes formula is $(n(n+1)/2)^2$.
  use (n * (n + 1) / 2 : ℚ);
  induction n <;> norm_num [ Finset.sum_range_succ ] at * ; linarith